// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class GenerateValues
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject generateValuesMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.GenerateValues";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Value("Value"),
		Caption("Caption"),
		BarValue("BarValue"),
		Entity_PieChart("MyFirstModule.Entity_PieChart");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public GenerateValues(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "MyFirstModule.GenerateValues"));
	}

	protected GenerateValues(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject generateValuesMendixObject)
	{
		if (generateValuesMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("MyFirstModule.GenerateValues", generateValuesMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a MyFirstModule.GenerateValues");

		this.generateValuesMendixObject = generateValuesMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'GenerateValues.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static myfirstmodule.proxies.GenerateValues initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return myfirstmodule.proxies.GenerateValues.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static myfirstmodule.proxies.GenerateValues initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.GenerateValues(context, mendixObject);
	}

	public static myfirstmodule.proxies.GenerateValues load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.GenerateValues.initialize(context, mendixObject);
	}

	public static java.util.List<myfirstmodule.proxies.GenerateValues> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<myfirstmodule.proxies.GenerateValues> result = new java.util.ArrayList<myfirstmodule.proxies.GenerateValues>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//MyFirstModule.GenerateValues" + xpathConstraint))
			result.add(myfirstmodule.proxies.GenerateValues.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Value
	 */
	public final java.lang.String getValue()
	{
		return getValue(getContext());
	}

	/**
	 * @param context
	 * @return value of Value
	 */
	public final java.lang.String getValue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Value.toString());
	}

	/**
	 * Set value of Value
	 * @param value
	 */
	public final void setValue(java.lang.String value)
	{
		setValue(getContext(), value);
	}

	/**
	 * Set value of Value
	 * @param context
	 * @param value
	 */
	public final void setValue(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String value)
	{
		getMendixObject().setValue(context, MemberNames.Value.toString(), value);
	}

	/**
	 * @return value of Caption
	 */
	public final java.lang.String getCaption()
	{
		return getCaption(getContext());
	}

	/**
	 * @param context
	 * @return value of Caption
	 */
	public final java.lang.String getCaption(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Caption.toString());
	}

	/**
	 * Set value of Caption
	 * @param caption
	 */
	public final void setCaption(java.lang.String caption)
	{
		setCaption(getContext(), caption);
	}

	/**
	 * Set value of Caption
	 * @param context
	 * @param caption
	 */
	public final void setCaption(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String caption)
	{
		getMendixObject().setValue(context, MemberNames.Caption.toString(), caption);
	}

	/**
	 * @return value of BarValue
	 */
	public final java.lang.String getBarValue()
	{
		return getBarValue(getContext());
	}

	/**
	 * @param context
	 * @return value of BarValue
	 */
	public final java.lang.String getBarValue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.BarValue.toString());
	}

	/**
	 * Set value of BarValue
	 * @param barvalue
	 */
	public final void setBarValue(java.lang.String barvalue)
	{
		setBarValue(getContext(), barvalue);
	}

	/**
	 * Set value of BarValue
	 * @param context
	 * @param barvalue
	 */
	public final void setBarValue(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String barvalue)
	{
		getMendixObject().setValue(context, MemberNames.BarValue.toString(), barvalue);
	}

	/**
	 * @return value of Entity_PieChart
	 */
	public final myfirstmodule.proxies.PieChart getEntity_PieChart() throws com.mendix.core.CoreException
	{
		return getEntity_PieChart(getContext());
	}

	/**
	 * @param context
	 * @return value of Entity_PieChart
	 */
	public final myfirstmodule.proxies.PieChart getEntity_PieChart(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.PieChart result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Entity_PieChart.toString());
		if (identifier != null)
			result = myfirstmodule.proxies.PieChart.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Entity_PieChart
	 * @param entity_piechart
	 */
	public final void setEntity_PieChart(myfirstmodule.proxies.PieChart entity_piechart)
	{
		setEntity_PieChart(getContext(), entity_piechart);
	}

	/**
	 * Set value of Entity_PieChart
	 * @param context
	 * @param entity_piechart
	 */
	public final void setEntity_PieChart(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.PieChart entity_piechart)
	{
		if (entity_piechart == null)
			getMendixObject().setValue(context, MemberNames.Entity_PieChart.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Entity_PieChart.toString(), entity_piechart.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return generateValuesMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.GenerateValues that = (myfirstmodule.proxies.GenerateValues) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "MyFirstModule.GenerateValues";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
