// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class PieChart
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject pieChartMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.PieChart";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		FinalValues("FinalValues"),
		FinalCaptions("FinalCaptions"),
		FinalBarValues("FinalBarValues");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public PieChart(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "MyFirstModule.PieChart"));
	}

	protected PieChart(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject pieChartMendixObject)
	{
		if (pieChartMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("MyFirstModule.PieChart", pieChartMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a MyFirstModule.PieChart");

		this.pieChartMendixObject = pieChartMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'PieChart.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static myfirstmodule.proxies.PieChart initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return myfirstmodule.proxies.PieChart.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static myfirstmodule.proxies.PieChart initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.PieChart(context, mendixObject);
	}

	public static myfirstmodule.proxies.PieChart load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.PieChart.initialize(context, mendixObject);
	}

	public static java.util.List<myfirstmodule.proxies.PieChart> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<myfirstmodule.proxies.PieChart> result = new java.util.ArrayList<myfirstmodule.proxies.PieChart>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//MyFirstModule.PieChart" + xpathConstraint))
			result.add(myfirstmodule.proxies.PieChart.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of FinalValues
	 */
	public final java.lang.String getFinalValues()
	{
		return getFinalValues(getContext());
	}

	/**
	 * @param context
	 * @return value of FinalValues
	 */
	public final java.lang.String getFinalValues(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.FinalValues.toString());
	}

	/**
	 * Set value of FinalValues
	 * @param finalvalues
	 */
	public final void setFinalValues(java.lang.String finalvalues)
	{
		setFinalValues(getContext(), finalvalues);
	}

	/**
	 * Set value of FinalValues
	 * @param context
	 * @param finalvalues
	 */
	public final void setFinalValues(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String finalvalues)
	{
		getMendixObject().setValue(context, MemberNames.FinalValues.toString(), finalvalues);
	}

	/**
	 * @return value of FinalCaptions
	 */
	public final java.lang.String getFinalCaptions()
	{
		return getFinalCaptions(getContext());
	}

	/**
	 * @param context
	 * @return value of FinalCaptions
	 */
	public final java.lang.String getFinalCaptions(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.FinalCaptions.toString());
	}

	/**
	 * Set value of FinalCaptions
	 * @param finalcaptions
	 */
	public final void setFinalCaptions(java.lang.String finalcaptions)
	{
		setFinalCaptions(getContext(), finalcaptions);
	}

	/**
	 * Set value of FinalCaptions
	 * @param context
	 * @param finalcaptions
	 */
	public final void setFinalCaptions(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String finalcaptions)
	{
		getMendixObject().setValue(context, MemberNames.FinalCaptions.toString(), finalcaptions);
	}

	/**
	 * @return value of FinalBarValues
	 */
	public final java.lang.String getFinalBarValues()
	{
		return getFinalBarValues(getContext());
	}

	/**
	 * @param context
	 * @return value of FinalBarValues
	 */
	public final java.lang.String getFinalBarValues(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.FinalBarValues.toString());
	}

	/**
	 * Set value of FinalBarValues
	 * @param finalbarvalues
	 */
	public final void setFinalBarValues(java.lang.String finalbarvalues)
	{
		setFinalBarValues(getContext(), finalbarvalues);
	}

	/**
	 * Set value of FinalBarValues
	 * @param context
	 * @param finalbarvalues
	 */
	public final void setFinalBarValues(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String finalbarvalues)
	{
		getMendixObject().setValue(context, MemberNames.FinalBarValues.toString(), finalbarvalues);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return pieChartMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.PieChart that = (myfirstmodule.proxies.PieChart) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "MyFirstModule.PieChart";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
